contentdir = "src"
baseurl = "https://go-hep.org/"
languageCode = "en-us"
title = "go-hep"
copyright = "go-hep"

license = "BSD"
licenselink = "https://codeberg.org/go-hep/hep/src/branch/main/LICENSE"
homepage = "https://go-hep.org"

theme = "hugo-material-docs"

tags = ["documentation", "sphinx"]

disqusShortname = ""
googleAnalytics = ""

# enable pygments (but use Chroma)
pygmentsCodeFencesGuessSyntax = true
pygmentsUseClasses = true
pygmentsUseClassic = false
pygmentsCodeFences = true

[params]
	name = "Go-HEP"

	description = "Writing HEP software with ease and Go"
	codeberg = "https://codeberg.org/go-hep"

	custom_css = []
	custom_js  = []

	permalink = "#"
	#highlightjs = "css/highlight.css"
	favicon = "favicon.ico"
	logo = "images/go-hep-logo.png"

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "black"
    	accent  = "blue"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

    [params.social]
    	codeberg = "go-hep/hep"
    	email    = "~sbinet/go-hep@lists.sr.ht"

[author]
	name = "The go-hep authors"

[permalinks]
	blog = "/:year/:month/:filename/"
	code = "/:filename/"

[taxonomies]
	tag = "tags"
	category = "categories"

[[menu.main]]
	name   = "Go HEP"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "News"
	url    = "news/"
	weight = 2

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 3

[[menu.main]]
	name   = "Tutorials"
	url    = "tutos/"
	weight = 4

[[menu.main]]
	name   = "Documentation"
	url    = "doc/"
	weight = 5

[[menu.main]]
	name   = "Downloads"
	url    = "downloads/"
	weight = 6

[[menu.main]]
	name   = "Contributing"
	url    = "contributing/"
	weight = 7

[[menu.main]]
	name   = "Users of Go-HEP"
	url    = "users/"
	weight = 8

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 9

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
